/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"



int *
sumar_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->arg1 + argp->arg2;
	printf("Suma ejecutandose del lado del servidor\n");

	return &result;
}

int *
restar_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->arg1 - argp->arg2;
	printf("Resta ejecutandose del lado del servidor\n");
	return &result;
}

int *
multiplicar_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->arg1 * argp->arg2;
	printf("Multiplicacion ejecutandose del lado del servidor\n");
	return &result;
}

double *
dividir_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static double  result;

	result = argp->arg3 / argp->arg4;
	printf("Division ejecutandose del lado del servidor\n");

	return &result;
}
