/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_entrada (XDR *xdrs, entrada *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	if (!xdr_double (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg4))
		 return FALSE;	
	return TRUE;
}
